swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer token authentication"
paths:
  /user/accounts:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching a specific user's account balances
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Attach Bearer JWT token
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              type: object
              properties:
                Id:
                  type: string
                  description: ID of the account
                balance:
                  type: number
                  description: Balance of the account
                name:
                  type: string
                  description: Name of the account
                accountNumber:
                  type: string
                  description: Number of the account
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching a specific user's account balance
      produces:
        - application/json
      parameters:
        - name: accountId
          in: path
          type: string
          required: true
          description: The ID of the account to retrieve
        - name: Authorization
          in: header
          type: string
          required: true
          description: Attach Bearer JWT token
      responses:
        '200':
          description: Single account retrieved successfully
          schema:
            type: object
            properties:
                Id:
                  type: string
                  description: ID of the account
                balance:
                  type: number
                  description: Balance of the account
                name:
                  type: string
                  description: Name of the account
                accountNumber:
                  type: string
                  description: Number of the account
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/transactions/account/{accountId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching a user's transactions
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountId
          in: path
          required: true
          type: string
          description: ID of the account
        - name: startDate
          in: query
          required: true
          type: string
          format: MM/YYYY
          description: Start date of the transactions (MM/YYYY)
        - name: endDate
          in: query
          required: true
          type: string
          format: MM/YYYY
          description: End date of the transactions (MM/YYYY)
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              type: object
              properties:
                transactionId:
                  type: string
                  description: ID of the transaction
                date:
                  type: string
                  format: date-time
                  description: Date of the transaction
                description:
                  type: string
                  description: Description of the transaction
                amount:
                  type: number
                  description: Amount of the transaction
                balance:
                  type: number
                  description: Balance after the transaction
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module
      summary: User Transaction Details API
      description: API for fetching details of a single transaction
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            type: object
            properties:
              transactionId:
                type: string
                description: ID of the transaction
              date:
                type: string
                format: date-time
                description: Date of the transaction
              description:
                type: string
                description: Description of the transaction
              amount:
                type: number
                description: Amount of the transaction
              balance:
                type: number
                description: Balance after the transaction
              transactionType:
                type: string
                description: Type of the transaction
              category:
                type: string
                description: Category of the transaction
              notes:
                type: string
                description: Notes about the transaction
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      security:
        - bearerAuth: []
      tags:
        - User Module
      summary: Update Transaction API
      description: API for updating a single transaction's category or notes
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: path
          description: ID of the transaction to be updated
          required: true
          type: string
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: The category of the transaction
              notes:
                type: string
                description: Additional notes for the transaction
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
definitions:
  AccountBalance:
    type: object
    properties:
      balance:
        type: number
        description: User's account balance